version: '3.1'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306" 
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=easyappointments
    volumes:
      - ea_mysql_data:/var/lib/mysql

  easyappointments:
    image: alextselegidis/easyappointments
    ports:
      - "80:80"
    environment:
      - DB_HOST=mysql
      - DB_NAME=easyappointments
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - DEBUG_MODE=true

volumes:
  ea_mysql_data: